# Generated by Django 4.2.4 on 2023-09-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='topic',
            new_name='subject',
        ),
    ]
