# Generated by Django 3.2.23 on 2024-07-01 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
