# Generated by Django 3.2.23 on 2024-07-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20240701_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
