# Generated by Django 3.2.23 on 2024-07-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
