# Generated by Django 3.2.23 on 2024-07-03 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_order_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
