# Generated by Django 3.2.23 on 2024-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_auto_20240704_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
    ]
