# Generated by Django 3.2.23 on 2024-06-29 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240629_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
