# Generated by Django 3.2.23 on 2024-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240629_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
