# Generated by Django 3.2.23 on 2024-07-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20240701_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
