# Generated by Django 3.2.23 on 2024-07-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20240701_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
